experiment_name: "ppo_tuning"
output_dir: "results/tuning"
method: "optuna"
n_trials: 50
n_timesteps: 1000000
eval_freq: 10000
n_eval_episodes: 10
n_jobs: -1
seed: 42
metric: "eval/mean_return"
direction: "maximize"